version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: seewritesay
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}  # 로컬 환경변수 사용
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
    container_name: seewritesay-app
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - DB_PASSWORD=${DB_PASSWORD}  # 로컬 환경변수 사용
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}  # 로컬 환경변수 사용
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}  # 로컬 환경변수 사용
      - JWT_SECRET=${JWT_SECRET}  # 로컬 환경변수 사용
      - OPENAI_API_KEY=${OPENAI_API_KEY}  # 로컬 환경변수 사용

volumes:
  pgdata:
