services:
  db:
    image: ${DOCKER_DB_IMAGE_NAME}
    container_name: ${DOCKER_DB_CONTAINER_NAME}
    restart: always
    environment:
      POSTGRES_DB: ${DOCKER_DB_POSTGRES_DBNAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DOCKER_DB_POSTGRES_PORT}
    volumes:
      - ${DOCKER_DB_POSTGRES_VOLUMES}

  app:
    build:
      context: .
    container_name: ${DOCKER_APP_CONTAINER_NAME}
    restart: always
    depends_on:
      - db
    ports:
      - ${DOCKER_APP_PORT}

    env_file:
      - .env

volumes:
  pgdata:
