server:
  address: ${APP_ADDRESS}
  port: ${APP_PORT}

spring:
  application:
    name: see-write-say

  config:
    import: >
      optional:classpath:code/nickname-words.yml,
      optional:classpath:environment/api-keys.yml,
      optional:classpath:environment/db-settings.yml,
      optional:classpath:environment/security-settings.yml,
      optional:classpath:environment/management-settings.yml

  web:
    resources:
      static-locations: classpath:/static/
---
spring:
  config.activate.on-profile: prod
  datasource:
    url: ${DATASOURCE_URL}

---
spring:
  config.activate.on-profile: local
  datasource:
    url: ${DATASOURCE_URL}
