server:
  address: 0.0.0.0
  port: 8080

spring:
  application:
    name: see-write-say

  datasource:
    driverClassName: ${DATASOURCE_DRIVER_CLASSNAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            scope:
              - profile
              - email
        provider:
          google:
            authorization-uri: "https://accounts.google.com/o/oauth2/auth"
            token-uri: "https://oauth2.googleapis.com/token"
            user-info-uri: "https://www.googleapis.com/oauth2/v3/userinfo"
            user-name-attribute: "sub"

jwt:
  secret: ${JWT_SECRET}
  validity-ms: 3600000

openai:
  api:
    key: ${OPENAI_API_KEY}
    url: "https://api.openai.com/v1/chat/completions"

---
spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: ${DATASOURCE_URL}

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: ${DATASOURCE_URL}