spring:
  datasource:
    url: ${DATASOURCE_URL}
    driverClassName: ${DATASOURCE_DRIVER_CLASSNAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: ${DATABASE_PLATFORM}
    ddl-auto: validate
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        jdbc:
          lob:
            non_contextual_creation: true